name=DevLab_HallEffect
version=1.0.0
author=UNIT Electronics MX
maintainer=Adrian Rabadan, Cesar Bautista, Jonathan Mejorado, Fernando Flores
sentence=Arduino library for the I2C Hall-effect sensor module using the DevLab Device Protocol (DDP).
paragraph=DevLab Hall Effect library to detect a magnet through DDP over I2C (Device ID 0x0109).
category=Sensors
url=https://github.com/UNIT-Electronics-MX/unit_devlab_hall_effect_50xx_library
architectures=*
includes=DevLab_HallEffect.h
depends=DevLabDDP, DevLab_Interface
